item {
  name: "/m/0k4j"
  id: 14
  display_name: "Car"
}
item {
  name: "/m/07r04"
  id: 88
  display_name: "Truck"
}
item {
  name: "/m/04_sv"
  id: 93
  display_name: "Motorcycle"
}
item {
  name: "/m/01jfm_"
  id: 102
  display_name: "Licence plate"
}
item {
  name: "/m/015qff"
  id: 190
  display_name: "Traffic light"
}
